// pages/list/list.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
      titleList:['A','B','C','D','E','F','G','H'
      ],
      contentList:[
        {
          'key':'A',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'B',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'C',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'D',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'E',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'F',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'d154581'
            },
            {
              'img':'',
              'name':'e154581'
            },
            {
              'img':'',
              'name':'f154581'
            },
            {
              'img':'',
              'name':'g154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        },
        {
          'key':'G',
          'row':[
            {
              'img':'',
              'name':'a154581'
            },
            {
              'img':'',
              'name':'b154581'
            },
            {
              'img':'',
              'name':'c154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            },
            {
              'img':'',
              'name':'h154581'
            },
            {
              'img':'',
              'name':'i154581'
            }
          ]
        }

      ],
      titleIndex:0,
      currentKey:"A"
  },

  changeId(e){
    //传给子元素  通过子元素调用达到改变颜色的地步
    //顺便改变key值利用scroll-view这个标签从而进行一些切换
    let { id } = e.detail;
    //console.log(key)
    //console.log(id,"===========")
    this.setData({
      titleIndex:id
    })
  },
  changekey(e){
    let {key}=e.detail;
    console.log(key,348)
    this.setData({
      currentKey: key
    })
  },
})